baseURL = "https://greenimpactfund.de/"
googleAnalytics = "G-QMVE8PNT7B"
languageCode = "en-us"
title = "GIFT - Green Impact Fund for Transformation"
disableKinds = ["taxonomy", "taxonomyTerm"]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true
[Params]
  images = ["img/social.png"]
  production = true
  description = "Green Impact Fund for Transformation"
  pdf = false
